name: BUILD

on:
  workflow_dispatch

jobs:
  build-dtb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - run: |
        sudo apt -y update
        sudo apt -y install device-tree-compiler gcc wget xz-utils tree
        sudo apt -y upgrade
    - name: build it 
      run: |
        cd dtb
        bash make_dtb.sh
        tree
    - uses: actions/upload-artifact@v3
      with:
        name: dtb 
        path: "./**/*.dtb"
